### ISSUE TITLE
This repo doesn't seem to match with jjtech0130.github.io

### ISSUE THREAD

**Issue by schoentoon** [JJTech0130/meta-multimc#4]
As your multimc build pulls directly from jjtech0130.github.io and this doesn't seem to match with this repo (it pulls https://jjtech0130.github.io/v1/net.minecraft/index.json to be exact).. The highest version available is 1.16-pre3, rather than 1.16.1

**Comment by JJTech0130** [comment]
Github Pages servers the meta files based on this repo. I have gotten a little behind on updateing this, but I will try to have an automation soon! Also 1.16.1 is now available.

**Comment by JJTech0130** [comment]
Also the v1 thing is because you are using an old build. Please update to a new one. You can just drop the files from the new tar.gz on top of the old so your instances and configs are saved.
